### ISSUE TITLE
0.1.0 release

### ISSUE THREAD

**Issue by dunglas** [dunglas/DunglasJsonLdApiBundle#20]
The goal is to release a 0.1.0 version when Symfony 2.7 will be out.

What do you think @sroze?

**Comment by sroze** [comment]
One month left, seams to be great ! What are the key features that still need to be implemented ?

**Comment by dunglas** [comment]
Key features seems already done but on the roadmap:
- [ ] Refactor the metadata factory (almost done)
- [ ] Fix to-many serialization to respect the Hydra spec (there is a thread about that on the Hydra mailing list)
