### ISSUE TITLE
Serialization group problem

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasJsonLdApiBundle#27]
I'm a little stuck and I really don't get what's wrong in my config.

I installed a [dunglas/api-platform](https://github.com/dunglas/api-platform) project with FOSUserBundle. I declared my own `User`, which extends the FOSUserBundle entity, as a resource to expose it to my API. So far so good, if I request `GET /api/users` I get the expected result.

Now I add `use Symfony\Component\Serializer\Annotation\Groups;` to my `Entity` class and use the annotation `@Groups({"user"})` to properties I which to expose to my API. The properties are properly redeclared as protected. Then in my `service.yml` I add:

```yml
calls:
    - [ "initNormalizationContext", [ { groups: [ "user" ] } ] ]
```

But the result is that no properties are exposed, I only get the `@id` and `@type` properties.

Any idea from where the error may come from?

**Comment by dunglas** [comment]
I get this working many times. Can you upload your skeleton on GitHub? I'll take a look.

**Comment by theofidry** [comment]
Sure: https://github.com/theofidry/Incipio (new-base branch)

**Comment by dunglas** [comment]
If you use annotations, you must add the following lines in `app/config/config.yml`:

```yaml
framework:
    # ...
    serializer:      { enable_annotations: true }
```

**Comment by dunglas** [comment]
Btw your project seems based on the Symfony Standard Edition and not on API Platform.

**Comment by theofidry** [comment]
Oh god... Can't believe I missed that. I did created it with `composer create-project dunglas/api-platform`, why make you thinks the opposite?

**Comment by dunglas** [comment]
Don't mind my comment about the standard edition... I was looking to another project in another tab...

**Comment by theofidry** [comment]
Kind of understandable given the hour :P
